<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ExceptionKnowledgeBase.Evaluator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExceptionKnowledgeBase.Contracts\ExceptionKnowledgeBase.Contracts.csproj" />
  </ItemGroup>

</Project>
